- name: Run Terraform from AWX EE
  hosts: all
  gather_facts: false
  tasks:
    - name: Terraform apply
      community.general.terraform:
        project_path: terraform/
        state: present
        force_init: true

