- name: Run Terraform from AWX EE
  hosts: all
  gather_facts: false
  tasks:
    - name: List files in project directory
      command: ls -l /runner/project

    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: /runner/project/terraform

    - name: Plan Terraform
      command: terraform plan
      args:
        chdir: /runner/project/terraform

    - name: Apply Terraform
      command: terraform apply -auto-approve
      args:
        chdir: /runner/project/terraform
